/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AsymptoticFreedom;
/**
 *
 * @author Geonmo
 */

public class AppletAF extends javax.swing.JApplet {
    /**
     * Initializes the applet AppletAF
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppletAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppletAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppletAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppletAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectedParticle = new javax.swing.ButtonGroup();
        thePotentialPanel = new javax.swing.JPanel();
        theOptionPanel = new javax.swing.JPanel();
        theParticleOption = new javax.swing.JLabel();
        theProtonButton = new javax.swing.JRadioButton();
        thePionButton = new javax.swing.JRadioButton();
        theNeutronButton = new javax.swing.JRadioButton();
        theKaonButton = new javax.swing.JRadioButton();
        theStartButton = new javax.swing.JButton();
        theViewPanel = new AsymptoticFreedom.ViewPanel();

        setBackground(new java.awt.Color(240, 240, 240));

        thePotentialPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout thePotentialPanelLayout = new javax.swing.GroupLayout(thePotentialPanel);
        thePotentialPanel.setLayout(thePotentialPanelLayout);
        thePotentialPanelLayout.setHorizontalGroup(
            thePotentialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        thePotentialPanelLayout.setVerticalGroup(
            thePotentialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        theParticleOption.setText("Particle");

        selectedParticle.add(theProtonButton);
        theProtonButton.setText("Proton");
        theProtonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theProtonButtonActionPerformed(evt);
            }
        });

        selectedParticle.add(thePionButton);
        thePionButton.setText("Pion+");
        thePionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thePionButtonActionPerformed(evt);
            }
        });

        selectedParticle.add(theNeutronButton);
        theNeutronButton.setText("Neutron");
        theNeutronButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theNeutronButtonActionPerformed(evt);
            }
        });

        selectedParticle.add(theKaonButton);
        theKaonButton.setText("Kaon+");
        theKaonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theKaonButtonActionPerformed(evt);
            }
        });

        theStartButton.setText("Start");
        theStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theStartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout theOptionPanelLayout = new javax.swing.GroupLayout(theOptionPanel);
        theOptionPanel.setLayout(theOptionPanelLayout);
        theOptionPanelLayout.setHorizontalGroup(
            theOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(theOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(theOptionPanelLayout.createSequentialGroup()
                        .addComponent(theParticleOption, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(theOptionPanelLayout.createSequentialGroup()
                        .addGroup(theOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(theOptionPanelLayout.createSequentialGroup()
                                .addComponent(theStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addComponent(theProtonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thePionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(theOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(theNeutronButton)
                            .addComponent(theKaonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))))
        );
        theOptionPanelLayout.setVerticalGroup(
            theOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theOptionPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(theParticleOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(theOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thePionButton)
                    .addComponent(theKaonButton))
                .addGap(18, 18, 18)
                .addGroup(theOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theNeutronButton)
                    .addComponent(theProtonButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(theStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        theViewPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        theViewPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                theViewPanelMouseDragged(evt);
            }
        });
        theViewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                theViewPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout theViewPanelLayout = new javax.swing.GroupLayout(theViewPanel);
        theViewPanel.setLayout(theViewPanelLayout);
        theViewPanelLayout.setHorizontalGroup(
            theViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        theViewPanelLayout.setVerticalGroup(
            theViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thePotentialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(theViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theOptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(theViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thePotentialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(theOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void resetViewPanel() {
        //ViewPanel.
    }
    
    private void thePionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thePionButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("pion selected.");
        theViewPanel.setParticle(1);
    }//GEN-LAST:event_thePionButtonActionPerformed

    private void theKaonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theKaonButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Kaon selected.");
        theViewPanel.setParticle(2);
    }//GEN-LAST:event_theKaonButtonActionPerformed

    private void theProtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theProtonButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Proton selected.");
        theViewPanel.setParticle(3);
    }//GEN-LAST:event_theProtonButtonActionPerformed

    private void theStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theStartButtonActionPerformed
        // TODO add your handling code here:
        theViewPanel.resetPanel();
    }//GEN-LAST:event_theStartButtonActionPerformed

    private void theNeutronButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theNeutronButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Neutron selected.");
        theViewPanel.setParticle(4);
    }//GEN-LAST:event_theNeutronButtonActionPerformed

    private void theViewPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theViewPanelMouseDragged
        // TODO add your handling code here:
        System.out.printf("x : %d, y : %d\n",evt.getX(), evt.getY());
    }//GEN-LAST:event_theViewPanelMouseDragged

    private void theViewPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theViewPanelMousePressed
        // TODO add your handling code here:
        System.out.printf("x : %d, y : %d\n",evt.getX(), evt.getY());
    }//GEN-LAST:event_theViewPanelMousePressed



    //private ViewPanel theViewPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup selectedParticle;
    private javax.swing.JRadioButton theKaonButton;
    private javax.swing.JRadioButton theNeutronButton;
    private javax.swing.JPanel theOptionPanel;
    private javax.swing.JLabel theParticleOption;
    private javax.swing.JRadioButton thePionButton;
    private javax.swing.JPanel thePotentialPanel;
    private javax.swing.JRadioButton theProtonButton;
    private javax.swing.JButton theStartButton;
    private AsymptoticFreedom.ViewPanel theViewPanel;
    // End of variables declaration//GEN-END:variables


    
}
